language: node_js

node_js:
  - 8.11.1

before_deploy:
  - bash ./bin/build/travis/before_deploy.sh

script: echo "npm test temporarily disabled"

deploy:
  - provider: pages
    local-dir: page_files
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    "on":
      all_branches: true
      condition: $TRAVIS_REPO_SLUG != fgpv-vpgf/plugins

  - provider: script
    skip_cleanup: true
    script: bash ./bin/build/travis/dist-build.sh
    "on":
      tags: true
      all_branches: true
      repo: fgpv-vpgf/plugins
